name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug', 'triage']
assignees:
  - ThatDudeJude

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: What happened?
      value: 'I encountered this bug'
    validations:
      required: true
  - type: textarea
    id: reproduce-bug
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the bug.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error '...'
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: device
    attributes:
      label: What device did the error occur on
      multiple: true
      options:
        - Mobile
        - Desktop
        - Tablet
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: markdown
    attributes:
      value: 'Thanks for completing our bug report form!'
